### ISSUE TITLE
Unable to use http-mock

### ISSUE THREAD

**Issue by shripathee** [tonycoco/heroku-buildpack-ember-cli#64]
We deploy our app to Heroku in the development/testing phase to share with our team. It would be great if http-mock works.

**Comment by tonycoco** [comment]
This is by design. I don't want the build pack to run any node server. It basically builds your Ember app and hosts that build statically via a simple Nginx setup.

If you want, there are "Build Hooks" as defined in the README that could be used to launch another process to serve your HTTP mocks.

But, the point is to have this work as a statically compiled site and not a server.
